services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_{{ wp_user }} # Nombre de contenedor único
    environment:
      MARIADB_ROOT_PASSWORD: "{{ wp_password }}_root" # Es buena práctica tener una pass de root diferente
      MARIADB_DATABASE: "db_{{ wp_user }}"
      MARIADB_USER: "{{ wp_user }}"
      MARIADB_PASSWORD: "{{ wp_password }}"
    volumes:
      - db_data_{{ wp_user }}:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wp_network_{{ wp_user }}

  wordpress:
    image: wordpress:latest
    container_name: wordpress_{{ wp_user }}
    depends_on:
      - mariadb
    ports:
      - "{{ wp_port }}:80" # Mapea el puerto único al puerto 80 del contenedor
    environment:
      WORDPRESS_DB_HOST: mariadb # Docker Compose resuelve 'mariadb' al contenedor correcto en la misma red
      WORDPRESS_DB_USER: "{{ wp_user }}"
      WORDPRESS_DB_PASSWORD: "{{ wp_password }}"
      WORDPRESS_DB_NAME: "db_{{ wp_user }}"
    volumes:
      - wp_files_{{ wp_user }}:/var/www/html
    restart: unless-stopped
    networks:
      - wp_network_{{ wp_user }}

volumes:
  db_data_{{ wp_user }}:
  wp_files_{{ wp_user }}:

networks:
  wp_network_{{ wp_user }}:
