---
- name: Instalar Drupal
  hosts: localhost
  become: yes
  tasks:

    - name: Descargar Drupal
      get_url:
        url: https://ftp.drupal.org/files/projects/drupal-10.2.2.tar.gz
        dest: /tmp/drupal.tar.gz

    - name: Crear directorio de destino
      file:
        path: /var/www/html/drupal
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Extraer Drupal
      unarchive:
        src: /tmp/drupal.tar.gz
        dest: /var/www/html/drupal
        remote_src: yes
        extra_opts: [--strip-components=1]

    - name: Establecer permisos a Drupal
      file:
        path: /var/www/html/drupal
        recurse: yes
        owner: apache
        group: apache
