---
- name: Desplegar Moodle
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    base_dir: "/var/www/html/proyecto_web/userscms/{{ usuario_id }}/moodle_{{ salt }}"
    moodledata_dir: "{{ base_dir }}/moodledata"
    db_name: "cms_{{ usuario_id }}_{{ salt }}"
    db_user: "user_{{ usuario_id }}_{{ salt }}"
    db_pass: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=20') }}"
    web_user: "apache"
    moodle_url: "http://localhost/userscms/{{ usuario_id }}/moodle_{{ salt }}"
    admin_user: "admin"
    admin_pass: "Admin1234!"
    admin_email: "admin@example.com"

  tasks:
    - name: 1. Instalar dependencias de Moodle
      become: yes
      ansible.builtin.dnf:
        name:
          - php
          - php-mysqlnd
          - php-xml
          - php-intl
          - php-zip
          - php-soap
          - php-opcache
          - php-mbstring
          - php-gd
          - php-curl
          - unzip
          - git
          - mariadb-server
          - mariadb
        state: present

    - name: 1.b Iniciar y habilitar MariaDB
      become: yes
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: 2. Crear la base de datos MariaDB
      community.mysql.mysql_db:
        name: "{{ db_name }}"
        state: present
        login_user: root
        login_password: root

    - name: 3. Crear el usuario de la base de datos
      community.mysql.mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_pass }}"
        priv: "{{ db_name }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: root

    - name: 4. Crear el directorio raíz de Moodle
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'

    - name: 5. Descargar Moodle desde GitHub
      become: yes
      ansible.builtin.git:
        repo: 'https://github.com/moodle/moodle.git'
        dest: "{{ base_dir }}"
        version: 'MOODLE_411_STABLE'

    - name: 6. Crear el directorio moodledata
      become: yes
      ansible.builtin.file:
        path: "{{ moodledata_dir }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0770'

    - name: 7. Dar permisos a la raíz de Moodle
      become: yes
      ansible.builtin.file:
        path: "{{ base_dir }}"
        recurse: yes
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        mode: '0755'

    - name: 8. Instalar Moodle desde CLI
      become: yes
      become_user: "{{ web_user }}"
      ansible.builtin.command: >
        php {{ base_dir }}/admin/cli/install.php
        --non-interactive
        --agree-license
        --wwwroot={{ moodle_url }}
        --dataroot={{ moodledata_dir }}
        --dbtype=mariadb
        --dbname={{ db_name }}
        --dbuser={{ db_user }}
        --dbpass={{ db_pass }}
        --fullname="Sitio Moodle {{ usuario_id }}"
        --shortname="Moodle {{ usuario_id }}"
        --adminuser={{ admin_user }}
        --adminpass={{ admin_pass }}
        --adminemail={{ admin_email }}
      environment:
        PATH: "/usr/bin:{{ ansible_env.PATH }}"

