---
- name: Desplegar PrestaShop (Modo Sin Sudoers)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    prestashop_version: "8.1.6"
    web_user: "apache"
    base_dir: "/var/www/html/proyecto_web/userscms/{{ usuario_id }}/{{ cms }}_{{ salt }}"

  tasks:
    # NOTA: Se asume que las dependencias (unzip, php-zip, etc.)
    # ya han sido instaladas manualmente en el servidor con 'sudo dnf install ...'

    - name: 1. Crear la base de datos MariaDB
      community.mysql.mysql_db:
        name: "{{ db_nombre }}"
        state: present
        login_user: root
        login_password: root

    - name: 2. Crear el usuario de la base de datos
      community.mysql.mysql_user:
        name: "{{ db_usuario }}"
        password: "{{ db_pass }}"
        priv: "{{ db_nombre }}.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: root

    - name: 3. Crear el directorio raíz para PrestaShop
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        mode: '0755'

    - name: 4. Descargar y descomprimir el paquete inicial de PrestaShop
      ansible.builtin.unarchive:
        src: "https://github.com/PrestaShop/PrestaShop/releases/download/{{ prestashop_version }}/prestashop_{{ prestashop_version }}.zip"
        dest: "{{ base_dir }}"
        remote_src: yes
      become: yes

    - name: 5. Descomprimir el archivo prestashop.zip principal
      ansible.builtin.unarchive:
        src: "{{ base_dir }}/prestashop.zip"
        dest: "{{ base_dir }}"
        remote_src: yes
      become: yes

    - name: 6. Limpiar los archivos de instalación sobrantes
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ base_dir }}/prestashop.zip"
        - "{{ base_dir }}/Install_PrestaShop.html"

    - name: 7. Archivos de usuario
      ansible.builtin.file:
        path: "{{ base_dir }}"
        state: directory
        owner: "{{ web_user }}"
        group: "{{ web_user }}"
        recurse: yes
      become: yes
