---
- name: Instalar WordPress
  hosts: localhost
  connection: local
  become: true
  gather_facts: false

  vars:
    wp_dir: /var/www/html/wordpress

  tasks:
    - name: Descargar WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Crear carpeta para Wordpress
      file:
        path: "{{ wp_dir }}"
        state: directory
        owner: apache
        group: apache
        mode: '0755'

    - name: Extraer WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: "{{ wp_dir }}"
        remote_src: yes
        creates: "{{ wp_dir }}/wp-config-sample.php"

    - name: Establecer permisos a WordPress
      file:
        path: "{{ wp_dir }}"
        owner: apache
        group: apache
        recurse: yes
        mode: '0755'
