---
- name: Desplegar WordPress para un usuario
  hosts: cms_servers
  become: yes
  vars:
    # Recibidas externamente o definidas aquí
    id_usuario: "123"  # Ejemplo. Se puede pasar por --extra-vars
    wp_db_name: "cms_user_{{ user_id }}_db"
    wp_db_user: "cms_user_{{ user_id }}_user"
    wp_db_password: "contraseña_segura_123"
    wp_db_host: "localhost"
    wp_title: "Sitio del Usuario {{ user_id }}"
    wp_admin_user: "admin"
    wp_admin_password: "adminpass123"
    wp_admin_email: "user{{ user_id }}@example.com"

  tasks:
    - name: Asegurar directorio de instalación de WordPress
      file:
        path: "/var/www/user_{{ user_id }}/wordpress"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Descargar última versión de WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz 
        dest: "/tmp/wordpress.tar.gz"
        mode: '0644'
        timeout: 60

    - name: Descomprimir WordPress
      unarchive:
        src: "/tmp/wordpress.tar.gz"
        dest: "/var/www/user_{{ user_id }}"
        remote_src: yes

    - name: Copiar wp-config.php desde plantilla
      template:
        src: "wp-config.php.j2"
        dest: "/var/www/user_{{ user_id }}/wordpress/wp-config.php"
      notify: Reiniciar Apache

    - name: Crear directorio uploads si no existe
      file:
        path: "/var/www/user_{{ user_id }}/wordpress/wp-content/uploads"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Establecer permisos correctos
      shell: |
        chown -R www-data:www-data /var/www/user_{{ user_id }}/wordpress
        find /var/www/user_{{ user_id }}/wordpress -type d -exec chmod 755 {} \;
        find /var/www/user_{{ user_id }}/wordpress -type f -exec chmod 644 {} \;

    - name: Crear archivo .htaccess si no existe
      copy:
        content: ""
        dest: "/var/www/user_{{ user_id }}/wordpress/.htaccess"
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Configurar permalinks (activar mod_rewrite)
      lineinfile:
        dest: "/etc/apache2/sites-available/000-default.conf"
        regexp: "AllowOverride None"
        replace: "AllowOverride All"
        backup: yes
      notify: Reiniciar Apache

    - name: Activar módulo rewrite de Apache
      apache2_module:
        name: rewrite
        state: present
      notify: Reiniciar Apache

  handlers:
    - name: Reiniciar Apache
      service:
        name: apache2
        state: restarted
