---
- name: Desplegar WordPress y MariaDB en Docker para un nuevo usuario
  hosts: tu_servidor_destino # El host donde se instalarán los contenedores
  become: yes # Se necesita para ejecutar comandos de Docker

  tasks:
    - name: Asegurar que Docker y el plugin Docker Compose estén instalados
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose-v2
        state: present
        update_cache: yes

    - name: Crear un directorio único para el sitio del usuario
      ansible.builtin.file:
        path: "/srv/sites/{{ wp_user }}" # /srv es un buen lugar para datos de servicios
        state: directory
        mode: '0755'

    - name: Generar el archivo docker-compose.yml desde la plantilla
      ansible.builtin.template:
        src: templates/docker-compose.yml.j2 # La plantilla que crearemos
        dest: "/srv/sites/{{ wp_user }}/docker-compose.yml"
        mode: '0644'

    - name: Levantar los contenedores con Docker Compose
      community.docker.docker_compose_v2:
        project_src: "/srv/sites/{{ wp_user }}" # Directorio donde está el docker-compose.yml
        state: present # Asegura que los servicios estén corriendo
